export type DreamSymbol = {
  slug: string;
  name: string; // "Cobra"
  title: string; // "Sonhar com cobra"
  summary: string;
  meanings: string[];
  psychological: string;
  ask: string[];
};

const s = (slug: string, name: string, summary: string, meanings: string[], psychological: string, ask: string[]): DreamSymbol => ({
  slug, name, title: `Sonhar com ${name.toLowerCase()}`, summary, meanings, psychological, ask,
});

export const DREAM_SYMBOLS: DreamSymbol[] = [
  s("cobra", "Cobra", "A cobra simboliza transformação, instinto e alertas sobre o que está oculto.",
    ["Mudança profunda se aproximando (a troca de pele)", "Um aviso sobre alguém ou algo que merece atenção", "Energia vital, sexualidade e cura"],
    "Para a psicologia analítica, a serpente representa o inconsciente e a energia instintiva. Ela aparece quando algo precisa ser integrado.",
    ["A cobra atacou, fugiu ou ficou parada?", "Você sentiu medo ou fascínio?", "Em que área da vida você está mudando?"]),
  s("agua", "Água", "A água representa emoções, inconsciente e fluxo da vida.",
    ["Água limpa: clareza emocional e renovação", "Água turva: confusão ou emoções reprimidas", "Ondas e enchentes: emoções intensas pedindo espaço"],
    "A água é o símbolo clássico do inconsciente. O estado da água reflete o estado das suas emoções.",
    ["A água estava calma ou agitada?", "Você nadava, afundava ou observava?", "Que emoção você evita sentir?"]),
  s("voar", "Voar", "Voar fala de liberdade, perspectiva e desejo de superar limites.",
    ["Liberdade e autoconfiança", "Fuga de responsabilidades", "Sonho lúcido: consciência dentro do sonho"],
    "Voar costuma surgir quando você ganha perspectiva sobre um problema ou deseja se libertar de uma pressão.",
    ["Voar era fácil ou exigia esforço?", "Você controlava a direção?", "Do que você quer se afastar?"]),
  s("cair", "Queda", "Cair em sonhos sinaliza insegurança, perda de controle ou necessidade de se soltar.",
    ["Medo de falhar ou perder algo", "Pressão no trabalho ou nos relacionamentos", "Convite a soltar o controle"],
    "A queda está ligada à sensação de falta de chão. Pode refletir estresse acumulado.",
    ["Onde sua vida está sem base firme?", "O que você tenta controlar demais?", "Você acordou antes do impacto?"]),
  s("dentes", "Dentes caindo", "Dentes caindo estão associados a ansiedade, imagem pessoal e medo de perdas.",
    ["Ansiedade com a aparência ou com o que os outros pensam", "Transições e mudanças de fase", "Preocupação com saúde ou com a família"],
    "Dentes simbolizam poder de mastigar e de se expressar. Perdê-los remete a vulnerabilidade.",
    ["Você anda preocupado(a) com julgamentos?", "Há uma conversa difícil pendente?", "Está passando por uma transição?"]),
  s("ser-perseguido", "Perseguição", "Ser perseguido(a) indica algo que você evita enfrentar.",
    ["Evitar um problema ou emoção", "Ansiedade e sobrecarga", "Uma parte de si ainda não aceita"],
    "O perseguidor costuma ser uma parte rejeitada de você — a 'sombra'. Enfrentá-lo no sonho muda o final.",
    ["Quem ou o que perseguia você?", "Você conseguiu se virar e encarar?", "O que você vem adiando resolver?"]),
  s("morte", "Morte", "Sonhar com morte quase nunca é presságio; é símbolo de fim de ciclo e renascimento.",
    ["Encerramento de uma fase", "Transformação profunda", "Luto, saudade ou necessidade de despedida"],
    "A morte no sonho representa transformação: algo em você muda de forma. É um símbolo comum de maturidade.",
    ["O que em sua vida está terminando?", "Você sentiu alívio ou tristeza?", "Há uma despedida necessária?"]),
  s("casa", "Casa", "A casa é você: seus cômodos representam camadas da sua psique.",
    ["Casa conhecida: seu mundo interior", "Cômodos desconhecidos: potenciais não explorados", "Casa em ruínas: necessidade de reforma interna"],
    "Jung via a casa como imagem da psique: porão (inconsciente), sótão (memória e espiritualidade).",
    ["Qual cômodo chamou atenção?", "A casa estava limpa ou bagunçada?", "Quem estava com você?"]),
  s("bebe", "Bebê", "Bebês simbolizam começos, projetos nascentes e vulnerabilidade.",
    ["Novo projeto ou ideia nascendo", "Necessidade de cuidar de si", "Desejo (ou medo) de maternidade/paternidade"],
    "O bebê é o símbolo do novo eu. Cuidar dele no sonho reflete como você cuida das suas novas ideias.",
    ["O bebê estava bem?", "Você se sentia preparado(a)?", "Que projeto precisa de cuidado agora?"]),
  s("ex", "Ex-parceiro(a)", "Sonhar com ex raramente é sobre a pessoa; é sobre o que ela representa.",
    ["Aprendizados e feridas não resolvidos", "Saudade de uma fase da vida", "Padrões afetivos se repetindo"],
    "A figura do ex funciona como espelho de qualidades ou dores que você ainda integra.",
    ["Que sentimento o sonho trouxe?", "Que qualidade dessa pessoa você busca?", "Que padrão você quer mudar?"]),
  s("gato", "Gato", "Gatos representam intuição, independência e mistério.",
    ["Intuição aguçada", "Necessidade de independência", "Traição ou dissimulação (gato arisco ou agressivo)"],
    "O gato é símbolo clássico do feminino intuitivo e da autonomia.",
    ["O gato era dócil ou arisco?", "Você se sentiu observado(a)?", "Onde falta ouvir a intuição?"]),
  s("cachorro", "Cachorro", "Cães simbolizam lealdade, proteção e amizade.",
    ["Amizade verdadeira", "Proteção e instinto de cuidado", "Cão agressivo: conflito com alguém próximo"],
    "O cão representa fidelidade e instinto domesticado: sua capacidade de confiar.",
    ["O cachorro era amigável?", "Quem ele lembrava?", "Em quem você confia?"]),
  s("aranha", "Aranha", "A aranha fala de criatividade, teia de relações e armadilhas.",
    ["Criatividade e destino tecido por você", "Sentir-se preso(a) numa situação", "Medo de algo que se esconde"],
    "Como símbolo arquetípico, a aranha é a tecelã do destino e também a figura devoradora.",
    ["Você estava na teia ou observando?", "Sentiu nojo, medo ou admiração?", "Que situação parece te prender?"]),
  s("fogo", "Fogo", "O fogo representa paixão, purificação e destruição criativa.",
    ["Paixão e energia vital", "Raiva e conflito", "Purificação: queimar o velho"],
    "O fogo transforma. Pode indicar emoções intensas pedindo expressão saudável.",
    ["O fogo aquecia ou destruía?", "Você tentou apagar?", "O que precisa ser transformado?"]),
  s("escola", "Escola / prova", "Sonhar que está em prova ou escola reflete sensação de avaliação.",
    ["Medo de ser julgado(a)", "Aprendizados da vida atual", "Síndrome do impostor"],
    "O sonho da prova aparece em adultos quando há pressão por desempenho.",
    ["Você estava preparado(a)?", "Quem avaliava?", "Onde você se sente testado(a) agora?"]),
  s("dinheiro", "Dinheiro", "Dinheiro fala de valor próprio, energia e segurança.",
    ["Autoestima e senso de valor", "Preocupação financeira real", "Trocas de energia (dar e receber)"],
    "O dinheiro simboliza o quanto você sente que vale e como lida com recursos.",
    ["Você ganhava ou perdia?", "Sentiu culpa ou alegria?", "O que você valoriza hoje?"]),
  s("ouro", "Ouro", "O ouro simboliza valor, sabedoria alcançada e potencial.",
    ["Descoberta do próprio valor", "Prosperidade que exige esforço", "Apego material"],
    "Na alquimia, ouro é a meta da transformação interior: o 'eu' integrado.",
    ["Onde estava o ouro?", "Você guardou ou compartilhou?", "Que valor interior você descobriu?"]),
  s("praia", "Praia / mar", "O mar é o inconsciente coletivo; a praia é a fronteira entre consciente e inconsciente.",
    ["Descanso e renovação", "Emoções vindo à tona", "Convite a mergulhar em si"],
    "A praia representa o limite entre o que sabemos e o que ainda é mistério.",
    ["O mar estava calmo?", "Você entrou na água?", "O que o horizonte despertou?"]),
  s("floresta", "Floresta", "A floresta é o desconhecido: caminho de autoconhecimento, e às vezes de medo.",
    ["Busca por identidade", "Sentir-se perdido(a)", "Natureza e instinto"],
    "Nos contos, a floresta é onde o herói se transforma. Entrar nela é aceitar o desconhecido.",
    ["Você estava perdido(a) ou explorando?", "Era dia ou noite?", "O que o guiou?"]),
  s("aviao", "Avião", "Aviões simbolizam ambições, projetos e transições de vida.",
    ["Projetos decolando ou atrasados", "Desejo de mudar de rumo", "Medo de perder o controle"],
    "O avião mostra o quanto você se sente no comando da própria trajetória.",
    ["Quem pilotava?", "O voo foi tranquilo?", "Para onde você queria ir?"]),
  s("carro", "Carro", "O carro representa o modo como você conduz sua vida.",
    ["Direção e controle", "Perda de freio: perda de controle", "Passageiro: delegar o destino"],
    "Quem dirige o carro no sonho mostra quem comanda sua vida hoje.",
    ["Você dirigia?", "O carro respondia?", "Onde está o freio na sua vida?"]),
  s("espelho", "Espelho", "O espelho convida à autoimagem e a ver o que não se vê.",
    ["Autoconhecimento", "Dúvida sobre identidade", "Confronto com a sombra"],
    "O espelho mostra a persona e a sombra. Quem você via nele?",
    ["O reflexo era você?", "O que mudou na imagem?", "O que você evita ver?"]),
  s("lua", "Lua", "A Lua representa o feminino, intuição, ciclos e emoções.",
    ["Intuição e emoções em destaque", "Fim e começo de ciclos", "Ligação com o feminino"],
    "A Lua é o arquétipo do inconsciente: o que ilumina de noite o que o dia esconde.",
    ["A Lua estava cheia ou nova?", "Como você se sentiu ao olhá-la?", "Que ciclo está mudando?"]),
  s("sol", "Sol", "O Sol simboliza consciência, vitalidade e sucesso.",
    ["Clareza, alegria e energia", "Reconhecimento", "Vitalidade e cura"],
    "O Sol é o símbolo do eu consciente e do heroísmo interior.",
    ["O sol aquecia ou queimava?", "O céu estava limpo?", "O que se ilumina na sua vida?"]),
  s("chuva", "Chuva", "A chuva simboliza limpeza, tristeza que lava e renovação.",
    ["Purificação emocional", "Melancolia", "Fertilidade e novos começos"],
    "A chuva é o choro da natureza: libera o que está contido.",
    ["Você se molhou?", "A chuva era forte ou suave?", "O que precisa ser lavado?"]),
  s("escada", "Escada", "Escadas falam de progresso, ascensão e conexão entre planos.",
    ["Evolução e metas", "Subida difícil: esforço necessário", "Descida: mergulho no inconsciente"],
    "A escada liga consciente e inconsciente — em qual direção você ia?",
    ["Subia ou descia?", "Os degraus eram firmes?", "Aonde levava?"]),
  s("porta", "Porta", "Portas simbolizam oportunidades, passagens e escolhas.",
    ["Oportunidade chegando", "Porta fechada: obstáculo ou limite", "Passagem para nova fase"],
    "Cada porta é uma escolha de vida; abrir ou fechar mostra seu momento.",
    ["A porta estava aberta?", "O que havia do outro lado?", "O que você teme atravessar?"]),
  s("borboleta", "Borboleta", "A borboleta é o símbolo universal da metamorfose.",
    ["Transformação pessoal", "Leveza e alma", "Renascimento"],
    "Psique em grego é 'borboleta' e 'alma'. É símbolo direto da transformação interior.",
    ["Que fase você está deixando?", "A borboleta pousou em você?", "Que beleza nasce agora?"]),
  s("lobo", "Lobo", "O lobo simboliza instinto, liberdade e pertencimento ao grupo.",
    ["Instinto e intuição", "Ameaça ou predador", "Busca de matilha / pertencimento"],
    "O lobo representa o selvagem interior: instinto livre que precisa de espaço.",
    ["O lobo era amigo ou ameaça?", "Estava sozinho ou em matilha?", "Onde você pede liberdade?"]),
  s("tubarao", "Tubarão", "Tubarão fala de ameaças ocultas e medos que rondam.",
    ["Ameaça profunda ou emoção intensa", "Alguém predatório no seu entorno", "Medo de ser engolido(a) por uma situação"],
    "Predador do mar: representa o inconsciente que ameaça emergir.",
    ["O tubarão atacou?", "Você estava na água ou no barco?", "O que ronda você?"]),
];

export const SYMBOL_BY_SLUG = Object.fromEntries(DREAM_SYMBOLS.map((x) => [x.slug, x])) as Record<string, DreamSymbol>;
